server.port=8080
push.api.key=changeme

# VAPID Keys (einmalig generieren mit: ant generate-vapid-keys)
vapid.public.key=BM_6rWcY-Ol77wUT9nvz1YQKL18v_rfTIaKzFLOrdYGyqrfVKtOK_5GH-j4F6SBs7sXz35NYwHgNTFQBrcaaDVw
vapid.private.key=zjXUUK3_OoJeobk5gEplbnj8Fo3XHtr_LZ9IbIfRKas
vapid.subject=mailto:admin@ttm.co.at

# H2 (Entwicklung):
# db.url=jdbc:h2:file:./data/pushdb
# db.username=sa
# db.password=
applicationServerKey
# MS SQL Server (Produktion) \u00e2\u0080\u0094 diese Zeilen aktivieren, H2 auskommentieren:
# db.url=jdbc:sqlserver://SERVER:1433;databaseName=DBNAME;encrypt=true;trustServerCertificate=true
# db.username=BENUTZER
# db.password=PASSWORT
db.url=jdbc:sqlserver://localhost:1433;databaseName=TESTTURNIER;encrypt=true;trustServerCertificate=true
db.username=sa
db.password=TTM

web.directory=web
